site:
  title: Cyoda Developer Documentation
  # Update this URL with your actual GitHub Pages URL
  # Format: https://<username>.github.io/<repository-name>
  url: https://cyoda-platform.github.io/cpl-doc-server
  start_page: Cyoda_User_Docs::index.adoc

content:
  sources:
    - url: https://github.com/Cyoda-platform/cpl-docs.git
      branches: [2.4.x,2.5.x,2.6.x,2.7.x,2.8.x,3.0.x,3.1.x,3.2.x,develop]
      start_paths:
        - cyoda-platform
        - cyoda-plugins
        - user-docs
        - technical-docs

output:
  dir: ./build/site
  clean: true

asciidoc:
  attributes:
    kroki-server-url: https://docs.cyoda.org/kroki
    kroki-fetch-diagram: true
  extensions:
    - "asciidoctor-kroki"

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: false
  supplemental_files: ./supplemental-ui